server:
  port: 9092

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
    datasource:
        data: classpath:/sql/data.sql
        driver-class-name: com.mysql.cj.jdbc.Driver
        platform: mysql
        schema: classpath:/sql/schema.sql
        url: jdbc:mysql://localhost/oauth?verifyServerCertificate=false&allowPublicKeyRetrieval=true&useSSL=false&requireSSL=false&useTimezone=true&serverTimezone=UTC
        username: root
        password: '1234'
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        generate-ddl: false
        hibernate:
            ddl-auto: none
        show-sql: true
      
## Configuring info endpoint
info:
  app:
    name: freight register
    description: Backend do servidor de cadastro de frete
    version: 1.0.0
