server:
  port: 9082
  
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9081/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/freight
    username: root
    password: '1234'
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    topic: first_topic
      
## Configuring info endpoint
info:
  app:
    name: freight register
    description: Backend do servidor de cadastro de frete
    version: 1.0.0
