server:
  port: 9084
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

feign:
  client:
    url:
      TestUrl: http://localhost:9092

zuul:
  ignoredServices: '*'
  host:
    max-total-connections: 1000
    max-per-route-connections: 1000
  routes:
    product-register-server:
      path: /api/v1/product/**
      sensitive-headers: null
      serviceId: product-register-server
      strip-prefix: false

ribbon:
  eureka:
    enabled: false

product-register-server:
  ribbon:
    listOfServers: localhost:9092

security:
  basic:
    enable: false   

management:
  security:
    enabled: false 
